/**
 * Generate Preset CSS Files
 *
 * Creates two sets of static CSS files for each featured brand preset:
 *
 * 1. tailwind/ — Pure Tailwind v4 output (via exportTailwindV4CSS)
 *    - OKLCH color scales, semantic role aliases (primary/secondary/tertiary)
 *
 * 2. shadcn/ — shadcn output (via exportShadcn)
 *    - Everything above + shadcn semantic tokens (background, card, etc.)
 *
 * Output: /static/presets/{tailwind,shadcn}/{preset-name}.css
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  generatePalette,
  exportTailwindV4CSS,
  exportShadcn,
  TEST_PALETTES,
  ensureAccessibility,
  type TestPalette,
} from "@sveltopia/colors";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = resolve(__dirname, "../static/presets");

// Featured presets to generate
const FEATURED_PRESET_IDS = [
  "sveltopia",
  "stripe",
  "spotify",
  "claude",
  "slack",
  "linear",
  "figma",
];

/**
 * Build a safe palette from a test preset
 */
function buildPalette(preset: TestPalette) {
  const { colors } = preset;
  const lightPalette = generatePalette({ brandColors: colors, mode: "light" });
  const darkPalette = generatePalette({ brandColors: colors, mode: "dark" });

  return ensureAccessibility({
    light: lightPalette.scales,
    dark: darkPalette.scales,
    _meta: {
      tuningProfile: lightPalette.meta.tuningProfile,
      inputColors: lightPalette.meta.inputColors,
      generatedAt: lightPalette.meta.generatedAt,
    },
  });
}

/**
 * Replace the generic generated header with a preset-specific one
 */
function replaceHeader(
  css: string,
  preset: TestPalette,
  framework: string,
): string {
  const header = `/**
 * ${preset.name} Color Preset (${framework})
 * Generated by @sveltopia/colors
 * Brand colors: ${preset.colors.join(", ")}
 */

`;
  return css.replace(/\/\*\*[\s\S]*?\*\/\n\n/, header);
}

/**
 * Generate Tailwind v4 preset (color scales + semantic roles only)
 *
 * Uses exportTailwindV4CSS — the same output users get with --format tailwind.
 * includeThemeBlock=false because app.css has @theme for runtime preset switching.
 */
function generateTailwindPreset(preset: TestPalette): string {
  const safePalette = buildPalette(preset);

  const css = exportTailwindV4CSS(safePalette, {
    includeSemanticRoles: true,
    lightSelector: ":root, .light",
    darkSelector: ".dark",
    includeThemeBlock: false,
  });

  return replaceHeader(css, preset, "Tailwind");
}

/**
 * Generate shadcn preset (color scales + semantic roles + shadcn tokens)
 *
 * Uses exportShadcn — the same output users get with --format shadcn.
 * includeThemeBlock=false and includeThemeInlineBlock=false because app.css has
 * @theme and @theme inline for runtime preset switching.
 */
function generateShadcnPreset(preset: TestPalette): string {
  const safePalette = buildPalette(preset);

  const css = exportShadcn(safePalette, {
    lightSelector: ":root, .light",
    darkSelector: ".dark",
    includeThemeBlock: false,
    includeThemeInlineBlock: false,
  });

  return replaceHeader(css, preset, "shadcn");
}

/**
 * Main: Generate all preset CSS files
 */
function main() {
  console.log("Generating preset CSS files...\n");

  const presets = TEST_PALETTES.filter((p: TestPalette) =>
    FEATURED_PRESET_IDS.includes(p.id),
  );

  // Ensure output directories exist
  const tailwindDir = resolve(OUTPUT_DIR, "tailwind");
  const shadcnDir = resolve(OUTPUT_DIR, "shadcn");
  mkdirSync(tailwindDir, { recursive: true });
  mkdirSync(shadcnDir, { recursive: true });

  for (const preset of presets) {
    // Tailwind preset
    const tailwindCSS = generateTailwindPreset(preset);
    const tailwindPath = resolve(tailwindDir, `${preset.id}.css`);
    writeFileSync(tailwindPath, tailwindCSS, "utf-8");

    // shadcn preset
    const shadcnCSS = generateShadcnPreset(preset);
    const shadcnPath = resolve(shadcnDir, `${preset.id}.css`);
    writeFileSync(shadcnPath, shadcnCSS, "utf-8");

    console.log(
      `  ${preset.name} -> tailwind/${preset.id}.css + shadcn/${preset.id}.css`,
    );
  }

  console.log(
    `\nGenerated ${presets.length * 2} preset files in ${OUTPUT_DIR}`,
  );
}

main();
