/**
 * Generate Preset CSS Files
 *
 * Creates static CSS files for each featured brand preset with:
 * - OKLCH color values (Tailwind v4 compatible)
 * - 50-950 scale naming (with 850 for Radix step 10)
 * - Semantic aliases (primary, secondary, tertiary)
 *
 * Output: /static/presets/{preset-name}.css
 */

import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
	generatePalette,
	exportTailwindV4CSS,
	TEST_PALETTES,
	ensureAccessibility,
	type TestPalette
} from '@sveltopia/colors';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = resolve(__dirname, '../static/presets');

// Featured presets to generate
const FEATURED_PRESET_IDS = ['sveltopia', 'stripe', 'spotify', 'claude', 'slack', 'linear', 'figma'];

/**
 * Generate CSS for a single preset using the library's export function
 */
function generatePresetCSS(preset: TestPalette): string {
	const { name, colors } = preset;

	// Generate light and dark palettes separately
	const lightPalette = generatePalette({ brandColors: colors, mode: 'light' });
	const darkPalette = generatePalette({ brandColors: colors, mode: 'dark' });

	// Construct a full Palette object for the export function
	const fullPalette = {
		light: lightPalette.scales,
		dark: darkPalette.scales,
		_meta: {
			tuningProfile: lightPalette.meta.tuningProfile,
			inputColors: lightPalette.meta.inputColors,
			generatedAt: lightPalette.meta.generatedAt
		}
	};

	const safePalette = ensureAccessibility(fullPalette);

	// Use the library's export function
	// Note: includeThemeBlock=false because our site has @theme in app.css
	// for runtime preset switching. End users using CLI get @theme included.
	let css = exportTailwindV4CSS(safePalette, {
		includeSemanticRoles: true,
		lightSelector: ':root, .light',
		darkSelector: '.dark',
		includeThemeBlock: false
	});

	// Add custom header for preset identification
	const header = `/**
 * ${name} Color Preset
 * Generated by @sveltopia/colors
 * Brand colors: ${colors.join(', ')}
 * Generated at: ${new Date().toISOString()}
 */

`;

	// Replace the generic header with preset-specific one
	css = css.replace(/\/\*\*[\s\S]*?\*\/\n\n/, header);

	return css;
}

/**
 * Main: Generate all preset CSS files
 */
function main() {
	console.log('Generating preset CSS files...\n');

	const presets = TEST_PALETTES.filter((p: TestPalette) =>
		FEATURED_PRESET_IDS.includes(p.id)
	);

	for (const preset of presets) {
		const css = generatePresetCSS(preset);
		const outputPath = resolve(OUTPUT_DIR, `${preset.id}.css`);
		writeFileSync(outputPath, css, 'utf-8');
		console.log(`  ${preset.name} -> ${preset.id}.css`);
	}

	console.log(`\nGenerated ${presets.length} preset files in ${OUTPUT_DIR}`);
}

main();
