import { describe, it, expect } from 'vitest';
import {
	exportTailwind,
	exportTailwindWithCSSVars,
	exportRadix,
	exportPanda
} from '../core/export-frameworks.js';
import { generatePalette } from '../core/palette.js';
import type { Palette, BrandColorInfo } from '../index.js';

// Helper to create a test palette
function createTestPalette(): Palette {
	const light = generatePalette({ brandColors: ['#FF4F00'] }); // Orange brand
	const dark = generatePalette({ brandColors: ['#FF4F00'], mode: 'dark' });

	return {
		light: light.scales,
		dark: dark.scales,
		_meta: {
			tuningProfile: light.meta.tuningProfile,
			inputColors: ['#FF4F00'],
			generatedAt: new Date().toISOString()
		}
	};
}

// Helper to create brand color info
function createBrandColorInfo(): BrandColorInfo[] {
	return [
		{
			hex: '#FF4F00',
			hue: 'orange',
			anchorStep: 9,
			isCustomRow: false
		},
		{
			hex: '#1A1A1A',
			hue: 'gray',
			anchorStep: 11,
			isCustomRow: false
		}
	];
}

describe('Framework Export Utilities', () => {
	describe('Tailwind Export', () => {
		it('exports Tailwind preset with 50-950 scale mapping', () => {
			const palette = createTestPalette();
			const output = exportTailwind(palette);

			// Should be valid JS module
			expect(output).toContain('export default {');

			// Should use 50-950 scale (Tailwind convention) - JSON.stringify uses double quotes
			expect(output).toContain('"50":');
			expect(output).toContain('"100":');
			expect(output).toContain('"200":');
			expect(output).toContain('"500":');
			expect(output).toContain('"800":');
			expect(output).toContain('"850":'); // Radix step 10
			expect(output).toContain('"900":');
			expect(output).toContain('"950":'); // Radix step 12

			// Should NOT have Radix 1-12 scale (as primary keys)
			expect(output).not.toMatch(/"1":\s*"#/);
		});

		it('exports with 1-12 scale when specified', () => {
			const palette = createTestPalette();
			const output = exportTailwind(palette, { scale: '1-12' });

			// Should use 1-12 scale
			expect(output).toContain('"1":');
			expect(output).toContain('"12":');

			// Should NOT have 50-950 scale
			expect(output).not.toContain('"50":');
		});

		it('includes dark mode plugin', () => {
			const palette = createTestPalette();
			const output = exportTailwind(palette);

			// Should have dark mode class strategy by default
			expect(output).toContain("darkMode: 'class'");

			// Should have plugins array with dark mode override
			expect(output).toContain('plugins:');
			expect(output).toContain("'.dark'");
		});

		it('uses media dark mode when specified', () => {
			const palette = createTestPalette();
			const output = exportTailwind(palette, { darkMode: 'media' });

			expect(output).toContain("darkMode: 'media'");
		});

		it('includes header comment with metadata', () => {
			const palette = createTestPalette();
			const output = exportTailwind(palette);

			expect(output).toContain('Generated by @sveltopia/colors');
			expect(output).toContain('Brand colors:');
			expect(output).toContain('Generated at:');
		});

		it('exports all 31 hue scales', () => {
			const palette = createTestPalette();
			const output = exportTailwind(palette);

			// Should have common hues (JSON uses double quotes)
			expect(output).toContain('"orange":');
			expect(output).toContain('"blue":');
			expect(output).toContain('"red":');
			expect(output).toContain('"gray":');
		});

		it('contains valid hex color values', () => {
			const palette = createTestPalette();
			const output = exportTailwind(palette);

			// Should have hex colors (JSON uses double quotes)
			expect(output).toMatch(/"#[0-9a-fA-F]{6}"/);
		});
	});

	describe('Tailwind CSS Variables Export', () => {
		it('exports Tailwind config with CSS variable references', () => {
			const palette = createTestPalette();
			const output = exportTailwindWithCSSVars(palette);

			// Should reference CSS variables
			expect(output).toContain('rgb(var(--color-');
			expect(output).toContain('<alpha-value>');
		});

		it('includes CSS variable definitions in comment', () => {
			const palette = createTestPalette();
			const output = exportTailwindWithCSSVars(palette);

			// Should have CSS comment with variable definitions
			expect(output).toContain(':root {');
			expect(output).toContain('.dark {');
			expect(output).toContain('--color-');
		});

		it('uses RGB space-separated values for Tailwind alpha support', () => {
			const palette = createTestPalette();
			const output = exportTailwindWithCSSVars(palette);

			// RGB values should be space-separated (e.g., "255 79 0")
			expect(output).toMatch(/--color-\w+-\d+: \d+ \d+ \d+;/);
		});
	});

	describe('Radix Export', () => {
		it('exports all 8 variants per hue', () => {
			const palette = createTestPalette();
			const output = exportRadix(palette);

			// For each hue, should have: base, alpha, P3, P3Alpha, dark versions
			// Using orange as example
			expect(output).toContain('export const orange =');
			expect(output).toContain('export const orangeA =');
			expect(output).toContain('export const orangeP3 =');
			expect(output).toContain('export const orangeP3A =');
			expect(output).toContain('export const orangeDark =');
			expect(output).toContain('export const orangeDarkA =');
			expect(output).toContain('export const orangeDarkP3 =');
			expect(output).toContain('export const orangeDarkP3A =');
		});

		it('uses Radix naming convention (hue1, hue2, ... hue12)', () => {
			const palette = createTestPalette();
			const output = exportRadix(palette);

			// Should use Radix naming: orange1, orange2, etc.
			expect(output).toContain('orange1:');
			expect(output).toContain('orange12:');
		});

		it('exports ESM by default', () => {
			const palette = createTestPalette();
			const output = exportRadix(palette);

			expect(output).toContain('export const');
			expect(output).not.toContain('module.exports');
		});

		it('exports CJS when specified', () => {
			const palette = createTestPalette();
			const output = exportRadix(palette, { format: 'cjs' });

			expect(output).toContain('module.exports');
			expect(output).toContain('const orange =');
		});

		it('includes alpha variants by default', () => {
			const palette = createTestPalette();
			const output = exportRadix(palette);

			// Alpha variants should have 8-digit hex codes
			expect(output).toContain('orangeA');
			expect(output).toMatch(/orangeA\d+: '#[0-9a-fA-F]{8}'/);
		});

		it('excludes alpha variants when disabled', () => {
			const palette = createTestPalette();
			const output = exportRadix(palette, { includeAlpha: false });

			expect(output).not.toContain('export const orangeA');
			expect(output).not.toContain('export const orangeDarkA');
		});

		it('includes P3 variants by default', () => {
			const palette = createTestPalette();
			const output = exportRadix(palette);

			expect(output).toContain('export const orangeP3');
			expect(output).toContain('color(display-p3');
		});

		it('excludes P3 variants when disabled', () => {
			const palette = createTestPalette();
			const output = exportRadix(palette, { includeP3: false });

			expect(output).not.toContain('export const orangeP3');
			expect(output).not.toContain('color(display-p3');
		});

		it('includes header comment with usage example', () => {
			const palette = createTestPalette();
			const output = exportRadix(palette);

			expect(output).toContain('Generated by @sveltopia/colors');
			expect(output).toContain('Drop-in replacement for @radix-ui/colors');
			expect(output).toContain('import { red, redA, redDark, redDarkA }');
		});

		it('produces valid hex colors', () => {
			const palette = createTestPalette();
			const output = exportRadix(palette);

			// Base colors should be 6-digit hex
			expect(output).toMatch(/orange1: '#[0-9a-fA-F]{6}'/);

			// Alpha colors should be 8-digit hex
			expect(output).toMatch(/orangeA1: '#[0-9a-fA-F]{8}'/);
		});

		it('produces valid P3 color values', () => {
			const palette = createTestPalette();
			const output = exportRadix(palette);

			// P3 values should have 4 decimal places
			expect(output).toMatch(/color\(display-p3 \d+\.\d{4} \d+\.\d{4} \d+\.\d{4}\)/);
		});

		it('produces valid P3 alpha color values', () => {
			const palette = createTestPalette();
			const output = exportRadix(palette);

			// P3 alpha values should have alpha component (3 decimal places)
			expect(output).toMatch(/color\(display-p3 \d+\.\d{4} \d+\.\d{4} \d+\.\d{4} \/ \d+\.\d{3}\)/);
		});
	});

	describe('Panda CSS Export', () => {
		it('exports Panda CSS preset', () => {
			const palette = createTestPalette();
			const brandInfo = createBrandColorInfo();
			const output = exportPanda(palette, brandInfo);

			expect(output).toContain("import { definePreset } from '@pandacss/dev'");
			expect(output).toContain('export const sveltopiaColors = definePreset({');
		});

		it('includes theme tokens', () => {
			const palette = createTestPalette();
			const brandInfo = createBrandColorInfo();
			const output = exportPanda(palette, brandInfo);

			expect(output).toContain('theme: {');
			expect(output).toContain('tokens: {');
			expect(output).toContain('colors:');
		});

		it('uses token format with value property', () => {
			const palette = createTestPalette();
			const brandInfo = createBrandColorInfo();
			const output = exportPanda(palette, brandInfo);

			// Panda tokens use { value: '#hex' } format
			expect(output).toMatch(/"value":\s*"#[0-9a-fA-F]{6}"/);
		});

		it('includes semantic tokens by default', () => {
			const palette = createTestPalette();
			const brandInfo = createBrandColorInfo();
			const output = exportPanda(palette, brandInfo);

			expect(output).toContain('semanticTokens:');
			expect(output).toContain('accent:');
			expect(output).toContain('brand:');
			expect(output).toContain('primary:');
			expect(output).toContain('secondary:');
		});

		it('maps accent to primary brand color', () => {
			const palette = createTestPalette();
			const brandInfo = createBrandColorInfo();
			const output = exportPanda(palette, brandInfo);

			// Should reference orange (the primary brand color)
			expect(output).toContain("'{colors.orange.");
		});

		it('includes accent scale (1-12 + DEFAULT)', () => {
			const palette = createTestPalette();
			const brandInfo = createBrandColorInfo();
			const output = exportPanda(palette, brandInfo);

			// Should have accent.1 through accent.12
			expect(output).toContain("1: { value: '{colors.orange.1}'");
			expect(output).toContain("12: { value: '{colors.orange.12}'");
			expect(output).toContain("DEFAULT: { value: '{colors.orange.9}'");
		});

		it('excludes semantic tokens when disabled', () => {
			const palette = createTestPalette();
			const brandInfo = createBrandColorInfo();
			const output = exportPanda(palette, brandInfo, { includeSemantic: false });

			expect(output).not.toContain('semanticTokens:');
			expect(output).not.toContain('accent:');
		});

		it('includes dark mode conditions', () => {
			const palette = createTestPalette();
			const brandInfo = createBrandColorInfo();
			const output = exportPanda(palette, brandInfo);

			expect(output).toContain('conditions:');
			expect(output).toContain("light: '[data-theme=light]");
			expect(output).toContain("dark: '[data-theme=dark]");
		});

		it('exports dark mode tokens separately', () => {
			const palette = createTestPalette();
			const brandInfo = createBrandColorInfo();
			const output = exportPanda(palette, brandInfo);

			expect(output).toContain('export const sveltopiaColorsDark =');
		});

		it('includes header comment with usage example', () => {
			const palette = createTestPalette();
			const brandInfo = createBrandColorInfo();
			const output = exportPanda(palette, brandInfo);

			expect(output).toContain('Generated by @sveltopia/colors');
			expect(output).toContain("import { sveltopiaColors } from './panda.preset'");
			expect(output).toContain('presets: [sveltopiaColors]');
		});

		it('handles empty brand color info gracefully', () => {
			const palette = createTestPalette();
			const output = exportPanda(palette, []);

			// Should still export without semantic tokens
			expect(output).toContain('export const sveltopiaColors');
			expect(output).not.toContain('semanticTokens:');
		});

		it('handles single brand color', () => {
			const palette = createTestPalette();
			const brandInfo: BrandColorInfo[] = [
				{
					hex: '#FF4F00',
					hue: 'orange',
					anchorStep: 9,
					isCustomRow: false
				}
			];
			const output = exportPanda(palette, brandInfo);

			// Primary should work
			expect(output).toContain("primary: { value: '{colors.orange.9}'");
			// Secondary should fall back to gray
			expect(output).toContain("secondary: { value: '{colors.gray.11}'");
		});
	});

	describe('Radix-Tailwind Scale Mapping', () => {
		it('maps Radix 1-12 to Tailwind 50-950 correctly', () => {
			const palette = createTestPalette();
			const tailwind = exportTailwind(palette);
			const radix = exportRadix(palette);

			// Extract orange color values from both exports
			// Radix orange1 should equal Tailwind orange.50
			const radixMatch = radix.match(/orange1: '(#[0-9a-fA-F]{6})'/);
			// Find orange section in tailwind then get the 50 value
			const tailwindOrangeSection = tailwind.match(/"orange":\s*\{[^}]*"50":\s*"(#[0-9a-fA-F]{6})"/s);

			expect(radixMatch).not.toBeNull();
			expect(tailwindOrangeSection).not.toBeNull();

			if (radixMatch && tailwindOrangeSection) {
				// Both should have the same hex value for step 1/50
				expect(radixMatch[1].toLowerCase()).toBe(tailwindOrangeSection[1].toLowerCase());
			}
		});

		it('maintains color accuracy across all 12 steps', () => {
			const palette = createTestPalette();

			// The mapping should be:
			// 1→50, 2→100, 3→200, 4→300, 5→400, 6→500
			// 7→600, 8→700, 9→800, 10→850, 11→900, 12→950

			const expectedMapping: Record<number, string> = {
				1: '50',
				2: '100',
				3: '200',
				4: '300',
				5: '400',
				6: '500',
				7: '600',
				8: '700',
				9: '800',
				10: '850',
				11: '900',
				12: '950'
			};

			// Verify the scale reference in the Tailwind output covers all steps
			const tailwind = exportTailwind(palette);

			for (const tailwindStep of Object.values(expectedMapping)) {
				expect(tailwind).toContain(`"${tailwindStep}":`);
			}
		});
	});
});
